server:
     port: ${API_SERVER_PORT:8888}
spring:
  datasource:
    driverClass: org.postgresql.Driver
    url: ${PG_URL:jdbc:postgresql://localhost:5432/wind}
    username: ${PG_UASERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/web-app/
    suffix: .html

logging:
  file: "./logs/veterok-api.log"
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"


